### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by 3ter** [cashew-olddew/godot-tutorials#6]
Hi @cashew-olddew ,

could you please add a license so we would be able to use code from your tutorials in our projects? E.g. CC-BY or Apache license would be great of course.

**Comment by cashew-olddew** [comment]
Thank you for pointing this out!

Actually, you do not have to credit me at all! While it is highly appreciated, it's not mandatory. Thus, the licensing of this would fall under [CC0](https://github.com/cashew-olddew/godot-tutorials/blob/main/LICENSE).

Additionally, the README on the project main page has been updated to also hold some information regarding the licensing. You can see the changes in [this commit](https://github.com/cashew-olddew/godot-tutorials/commit/150d8ab3d1aba87e204d3c47df77b33b2510a354).
